### ISSUE TITLE
com.google.firebase:firebase-ads 下载不到 vpn原因?

### ISSUE THREAD

**Issue by ab503044120** [yeungeek/monkey-android#4]
Error:Could not find com.google.firebase:firebase-core:9.0.0.
Required by:
    monkey-android-master:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by yeungeek** [comment]
最新的可以参考下
https://firebase.google.com/docs/android/setup
这个主要广告部分，如果你们用不到，可以在声明和代码中删除的
我当时是为测试下这个最新的firebase项目

**Comment by ab503044120** [comment]
已解决打开sdk更新的工具,然后更新google Repository到最新就可以了

**Comment by yeungeek** [comment]
ok，欢迎参与这个项目，有兴趣可以提供一些建议和意见。
后续会优化mvp模式
