### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [yeungeek/monkey-android#5]
Would you consider publishing the `.apk` file on Github (e.g. with `releases/`), so folks without Playstore access have a chance to grab it as well? You might even consider pushing it to F-Droid (or I could offer to pick up the Github-published `.apk` to be placed into [my repo](https://android.izzysoft.de/repo) ;)

**Comment by yeungeek** [comment]
Sorry, the reply is too late, apk has been uploaded.
Thanks to attention to the project

**Comment by IzzySoft** [comment]
Better late than never :smile_cat: Thanks a lot!

For some additional attention, see [my Github app list](https://android.izzysoft.de/applists/category/named/network_techsites#group_910) and find your app in [my F-Droid compatible repository](https://apt.izzysoft.de/fdroid/index/apk/com.yeungeek.monkeyandroid). If you could attach the `.apk` with your `releases/` (see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help: an easy thing to do, takes less than a minute per release) and let me know (e.g. by updating this issue once more), the app could be automatically updated in the repo – which then would happen within ~24h of you're adding it, usually.

**Comment by yeungeek** [comment]
Wow, i have uploaded it to `releases/`.
Please check it, thanks.

**Comment by IzzySoft** [comment]
Superb! That makes auto-update easy now. Adjusted the metadata in my repo accordingly – and as indicated, whenever you create a new tag and attach an `.apk` to it, the update should be available within ~24h in my repo. Thanks a lot, also in the name of all other "Googleplay abstinents" :smile_cat:
