### ISSUE TITLE
hello! good project!

### ISSUE THREAD

**Issue by coderyi** [yeungeek/monkey-android#6]
你好我是MonkeyforGitHub的作者coderyi，我可以在我的readme里面加入monkey-android的链接吗？

**Comment by yeungeek** [comment]
最近这几个月太忙了点，这个项目都没有怎么更新的，我直接pull request吧

**Comment by coderyi** [comment]
非常感谢！感觉很有缘啊！能写同一个

**Comment by yeungeek** [comment]
哈哈，的确有缘啊，不过还是你的项目完善
最近在看weex，准备用weex来重写一个

**Comment by coderyi** [comment]
可以啊！我之前用weex写过一点点，https://github.com/coderyi/hello-weex ,你怎么想起来用weex

**Comment by yeungeek** [comment]
正好在学习中的
